FROM docker.io/library/rust:latest
RUN apt update && apt install -y musl-tools musl-dev libssl-dev pkg-config musl-tools clang llvm coreutils postgresql
RUN cargo install sea-orm-cli
COPY ./ /workspace
CMD [ "tail", "-f" ]