//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "chattype")]
pub enum Chattype {
    #[sea_orm(string_value = "channel")]
    Channel,
    #[sea_orm(string_value = "group")]
    Group,
    #[sea_orm(string_value = "private")]
    Private,
    #[sea_orm(string_value = "supergroup")]
    Supergroup,
}
